const EVENT_TYPES = {
  TASK_SUBMITTED: "TASK_SUBMITTED",
  TASK_STARTED: "TASK_STARTED",
  TASK_RETRY_SCHEDULED: "TASK_RETRY_SCHEDULED",
  TASK_SUCCEEDED: "TASK_SUCCEEDED",
  TASK_FAILED: "TASK_FAILED",
  TASK_CANCELLED: "TASK_CANCELLED",
};

module.exports = EVENT_TYPES;
