const EVENT_TYPES = {
  TASK_SUBMITTED: "TASK_SUBMITTED",
  TASK_STARTED: "TASK_STARTED",
  ATTEMPT_FAILED: "ATTEMPT_FAILED",
  RETRY_SCHEDULED: "RETRY_SCHEDULED",
  TASK_SUCCEEDED: "TASK_SUCCEEDED",
  TASK_FAILED: "TASK_FAILED",
  TASK_BLOCKED: "TASK_BLOCKED",
  TASK_CANCELLED: "TASK_CANCELLED",
  TASK_RECOVERED: "TASK_RECOVERED",
};

module.exports = EVENT_TYPES;