const TASK_STATUS = {
  WAITING: "WAITING",
  RUNNING: "RUNNING",
  RETRY_WAIT: "RETRY_WAIT",
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
  BLOCKED: "BLOCKED",
  CANCELLED: "CANCELLED",
};

module.exports = TASK_STATUS;